# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bhLCrqWP3EunxAnud7id6UDMnpPZ4c8N
"""

print ("Name: Shekoni Olaitan Comfort")
print ("Email: shekoniolaitan77@gmail.com")
print ("Language: Python")
print ("Biostack: Genomics")
print ("Slack_Username: Hollainphinity")



